#ifndef SET_CMPP_IO_MACROS_H_
#define SET_CMPP_IO_MACROS_H_

#define CMPP_IO_ATT_NOT_FOUND -1
#define CMPP_IO_DIM_NOT_FOUND -1
#define CMPP_IO_VAR_NOT_FOUND -1
#define CMPP_IO_FILE_NOT_FOUND -1
#define CMPP_IO_GLOBAL_ATT -1
#define CMPP_IO_NC_UNLIMITED -1
#define CMPP_IO_FILE_DIM -1
#define CMPP_IO_TRUE 0
#define CMPP_IO_FALSE 1

/*String lengths.*/
#define CMPP_IO_EMS 512
#define CMPP_IO_MAX_ATT_NAME_LEN 129
#define CMPP_IO_MAX_DIM_NAME_LEN 128
#define CMPP_IO_MAX_VAR_NAME_LEN 128
#define CMPP_IO_MAX_FILE_NAME_LENGTH 512
#define CMPP_IO_MAX_ATT_STR_LEN 513
#define XLG_STR_LEN 512


#define CMPP_WRONLY 100
#define CMPP_RDONLY 101
#define CMPP_APPEND 102
#define CMPP_OVERWR 103
#define CMPP_ASCII 200
#define CMPP_NETCDF 203
#define CMPP_HDF5 204
#define CMPP_DELETE_FILE 501
#define CMPP_KEEP_FILE 502

#define CMPP_IO_NC_CHAR 6
#define CMPP_IO_NC_BYTE 4
#define CMPP_IO_NC_SHORT 3
#define CMPP_IO_NC_INT 5
#define CMPP_IO_NC_FLOAT 2
#define CMPP_IO_NC_DOUBLE 1

/*
#define CMPP_IO_MAX_NUM_FILES 2048
*/

#define CMPP_IO_MAX_NUM_NETCDF_FILES_ALLOWED 1024
#define CMPP_IO_MAX_NUM_REGULAR_FILES_ALLOWED 1024
#define CMPP_IO_MAX_NUM_HDF5_FILES_ALLOWED 1024
#define CMPP_IO_MAX_GLOBAL_ATTS_PER_FILE 64
#define CMPP_IO_MAX_DIMS_PER_FILE 64
#define CMPP_IO_MAX_VARS_PER_FILE 128
#define CMPP_IO_MAX_ATTS_PER_VAR 64
#define CMPP_IO_MAX_DIMS_PER_VAR 64
#define CMPP_IO_MAX_METADATA_BYTES_PER_FILE 65536
#define CMPP_IO_MAX_ATT_NUM_VALS 4096
#define CMPP_IO_MAX_DIM_LEN 65536

#define ATT_PTR 1
#define DIM_PTR 2
#define VAR_PTR 3
#define NC_FILE_PTR 4
#define CMPP_IO_INDEX_NOT_FOUND -1

#define CMPP_IO_FREAD_MAX_NUM_VALS 2147483647
#define CMPP_IO_FREAD_MAX_VAL_WIDTH 64
#define CMPP_IO_CHAR 1
#define CMPP_IO_INT 2
#define CMPP_IO_FLOAT 3
#define CMPP_IO_DOUBLE 4

#endif
